
server:
  port: 8000


hasard: ${random.uuid}

hello:
  greeting: Guten tag
  position: 1
  style: upper
  style-case: UpperCase


---
spring.config.activate.on-profile: prod

logging:
  file:
    name: server.log
    path: .

  level:
    root: WARN
    '[org.formation]': debug